name: Release

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Pakage Addon
      run: (cd .. && zip -r PyClone/PyClone.zip PyClone -x '*.git*')
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "PyClone.zip"
        token: ${{ secrets.GITHUB_TOKEN }}

