name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Pakage Addon
      run: zip -r PyClone.zip .
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "PyClone.zip"
        token: ${{ secrets.GITHUB_TOKEN }}

